# Generated by Django 5.0.6 on 2024-06-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockwardrobeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='image',
            field=models.ImageField(default='/skins/default.png', upload_to='skins'),
        ),
    ]
